language: objective-c
os: osx
osx_image: xcode9

script:
  - xcodebuild clean build test -workspace StackViewDevelop.xcworkspace -scheme StackViewDevelop -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'
