language: objective-c
os: osx
osx_image: xcode9

script:
  - xcodebuild clean build -workspace StackViewDevelop.xcworkspace -scheme StackViewDevelop -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0'
